
name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm install, build and test
      run: |
        npm install
        npm run lint --if-present
        npm run test
        npm run build
      env:
        CI: true
        TEST_API_TOKEN: ${{secrets.TEST_API_TOKEN}}
