name: Release

on:
  release:
    types: published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint --if-present
        npm run test:coverage --if-present
        npm run build
      env:
        CI: true
        TEST_API_TOKEN: ${{secrets.TEST_API_TOKEN}}
    - name: npm publish
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm publish --access public
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        TEST_API_TOKEN: ${{secrets.TEST_API_TOKEN}}
